name: generalized-workflow

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
